weight_decay: 0.0
steps: 320_000 #160_000
batch_size: 20
num_workers: 10
save_every: 10_000
grad_clip: 1.0
gamma_steplr: 0.5
training_res: [800, 608]
device_num: 0
save_ckpt_every: 500
optimizer:
  lr: 2.e-4
  warm_up_steps: 2000
  cosine_lr: true
