name: pose_modified_panormic_feat
enhance_type: "both"

pose_enhancer:
  name: pose_separate
  input_data: "image"  # "image" or "feat"
  # Limit predicted relative rotation so that two cameras' FOVs still overlap at infinity.
  # When enabled, we clamp yaw/pitch within each camera's FOV, preserving roll as much as possible.
  limit_pose_to_fov_overlap: false
  # Small margin (in degrees) subtracted from FOV to avoid numerical boundary cases.
  fov_overlap_epsilon_deg: 0.5
  pose_encoder:
    num_layers: 34
    weights_init: "pretrained"
    num_input_images: 2
    pretrained: True
    channels: 3   # images 3 feat 128
  pose_decoder:
    num_input_features: 1
    num_frames_to_predict_for: 2
    stride: 1
    num_view_per_frame: 1    
    joint_pose: true    # for relative pose with multi-view, if true, the pose is the mean of all views
  
feat_enhancer:
  name: panormic_feat
  panormic_radius: 0.5
  panormic_resolution: [1.0, 1.0]
  