name: pose_modified_panormic_feat
enhance_type: "both"

pose_enhancer:
  name: pose_hier
  input_data: "image"  # "image" or "feat"
  use_norm_xy: true   # 是否给每个view添加归一化xy坐标，对应channel需要加上2个通道，用于后续特征融合
  # Limit predicted relative rotation so that two cameras' FOVs still overlap at infinity.
  # When enabled, we clamp yaw/pitch within each camera's FOV, preserving roll as much as possible.
  limit_pose_to_fov_overlap: false
  # Small margin (in degrees) subtracted from FOV to avoid numerical boundary cases.
  fov_overlap_epsilon_deg: 0.5
  pose_encoder:
    name: resnet_hier
    num_layers: 34
    weights_init: "pretrained"
    num_input_images: 2
    pretrained: True
    channels: 3   # images 3 feat 128
    eca_fusion_reduce: false
    spatila_softmax: false
    spatila_softmax_tau: 0.2
    use_norm_xy: false    # normal xy v2
    attn_encoder: null
  pose_decoder:
    name: pose_decoder
    num_input_features: 1
    num_frames_to_predict_for: 2
    stride: 1
    num_view_per_frame: 1    
    joint_pose: true    # for relative pose with multi-view, if true, the pose is the mean of all views
  
feat_enhancer:
  name: panormic_feat
  panormic_radius: 0.5
  panormic_resolution: [1.0, 1.0]
  